Repository Mellanox/libvma, pull requests merged in 2018-05, with the labels that each got.

#611 issue: 1354251 Fix statistics for socketXreme income data
  src/vma/sock/sockinfo_tcp.cpp
  src/vma/sock/sockinfo_udp.cpp
  src/vma/sock/sockinfo_udp.h
Labels: 8.6.x

#613 issue: 1357010 Fix setsockopt(IP_MULTICAST_IF) with struct mreq
  src/vma/sock/sockinfo_udp.cpp
Labels: 8.6.x

#605 issue: 1182150 Support HW RX timestamp in SocketXtreme
  src/vma/dev/cq_mgr.cpp
  src/vma/sock/sockinfo_udp.cpp
  src/vma/vma_extra.h
Labels: 8.6.x

#608 issue: 1375982 Error message while libnl-route-3-dev is not installed
  config/m4/nl.m4
Labels: 8.6.x

#610 Enhance striding rq
  src/vma/dev/ring_eth_cb.cpp
  src/vma/dev/ring_eth_cb.h
Labels: 8.6.x

#615 issue: 321712 ****************** VMA 8.6.1 *******************
  configure.ac
  journal.txt
Labels: 8.6.x

#617 issue: 321712 ****************** VMA 8.6.2 *******************
  configure.ac
  journal.txt
Labels: 8.6.x

#620 issue: 321712 ****************** VMA 8.6.3 *******************
  configure.ac
  journal.txt
Labels: 8.6.x

#625 issue: 321712 ****************** VMA 8.6.4 *******************
  configure.ac
  journal.txt
Labels: 8.6.x

#616 issue: 1382889 Add Tx statistics to ring
  src/stats/stats_printer.cpp
  src/stats/stats_reader.cpp
  src/vma/dev/ring_simple.cpp
  src/vma/util/vma_stats.h
Labels: 8.6.x, In Regression

#598 issue: 1338066 Fix disable flow tag for unicast flows
  src/vma/dev/ring_simple.cpp
  src/vma/sock/sockinfo.h
  src/vma/sock/sockinfo_tcp.h
  src/vma/sock/sockinfo_udp.cpp
  src/vma/sock/sockinfo_udp.h
Labels: 8.6.x, In Regression

#622 issue: 1387232 Fix creating write permission files
  src/stats/stats_printer.cpp
  src/stats/stats_publisher.cpp
  src/stats/stats_reader.cpp
  src/vma/util/sys_vars.h
  src/vma/util/utils.h
  src/vma/util/vma_stats.h
Labels: 8.6.x

#628 issue: 1398946 Fix issue with incorrect ring_eth_cb creation
  contrib/valgrind/valgrind_vma.supp
  src/vma/dev/ring_eth_cb.cpp
  src/vma/dev/ring_eth_cb.h
  src/vma/dev/ring_eth_direct.cpp
  src/vma/dev/ring_simple.cpp
  src/vma/dev/ring_simple.h
Labels: 8.6.x, In Regression, bug

#633 issue: 321712 ****************** VMA 8.6.6 *******************
  configure.ac
  journal.txt
Labels: 8.6.x

#631 issue: 1403631 support master slave for qp direct
  src/vma/dev/qp_mgr_eth_direct.cpp
  src/vma/dev/qp_mgr_eth_direct.h
  src/vma/dev/qp_mgr_eth_mlx5.cpp
  src/vma/dev/qp_mgr_eth_mlx5.h
Labels: 8.6.x
