Repository Mellanox/libvma, pull requests merged in 2019-08, with the labels that each got.

#843 issue: 1798908 Fix daemon agent initialization in case fork() usage
  src/vma/main.cpp
Labels: 8.8.x, In Regression, bug

#842 issue: 1797193 Return ECONNABORTED as error value for accept()
  src/vma/sock/sockinfo_tcp.cpp
Labels: 8.9.x, In Regression, bug

#845 issue: 1718617 Update valgrind suppression file
  contrib/valgrind/valgrind_vma.supp
  src/vma/dev/cq_mgr_mlx5.cpp
  src/vma/dev/ib_ctx_handler.cpp
  src/vma/dev/qp_mgr.cpp
  src/vma/ib/mlx5/ib_mlx5.cpp
  src/vma/ib/mlx5/ib_mlx5_hw.cpp
Labels: 8.9.x, In Regression, enhancement
