Repository Mellanox/libvma, pull requests merged in 2019-09, with the labels that each got.

#851 issue: 1859490 Improve migration error processing
  src/vma/dev/ring_allocation_logic.cpp
  src/vma/dev/ring_allocation_logic.h
  src/vma/sock/sockinfo.cpp
Labels: 8.9.x, In Regression, bug

#852 issue: 1902084 Add deprecated message for Multi Packet RQ
  config/m4/verbs.m4
  src/vma/sock/sock-redirect.cpp
Labels: 8.9.x, In Regression, enhancement

#853 issue: 1894523 Disable BF usage under VMs
  src/vma/dev/qp_mgr_eth_mlx5.cpp
Labels: 8.9.x, In Regression, bug

#856 issue: 321712 ****************** VMA 8.9.3 *******************
  configure.ac
  journal.txt
Labels: 8.9.x

#855 issue: 1898614 Fix badhead tail access in mp_cq
  src/vma/dev/cq_mgr_mp.cpp
  src/vma/dev/cq_mgr_mp.h
  src/vma/dev/qp_mgr_mp.h
Labels: 8.9.x, In Regression, bug

#859 issue: 321712 ****************** VMA 8.9.4 *******************
  configure.ac
  journal.txt
Labels: 8.9.x
